version: "3.9"
services:
  db:
    image: postgres:16
    container_name: rangpur_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: rangpur_hearing
    ports:
      - "5432:5432"
    volumes:
      - rangpur_pg_data:/var/lib/postgresql/data

volumes:
  rangpur_pg_data: